<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageIcon>DMNuGet.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>10.0.1</Version>
    <Title>.NET Aspire MailDev Host</Title>
    <PackageProjectUrl>https://github.com/marqdouj/dotnet.aspire.maildev</PackageProjectUrl>
    <PackageTags>Aspire MailDev</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <Authors>Douglas Marquardt</Authors>
    <Copyright>© Douglas Marquardt. All rights reserved.</Copyright>
    <Description>.NET Aspire MailDev Host</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\DMNuGet.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
